device: add leobog hi75
carlossless/sinowealth-kb-tool pull request #74
Opened 2024-04-25 22:55 UTC by Mooyeee

2024-04-27 14:30 UTC, carlossless requested changes
Hey, thanks for the device report & PR!

Before I can merge this in though you should add the device info to src/part.rs and remove the table reformating in README.md

2024-04-27 14:30 UTC, carlossless commented on README.md
> +| Model                                                                                                                                                                    | ISP MD5
Please don't reformat all of these tables. Just add your device info in the alphabetical order this list is sorted in.

2024-04-27 21:02 UTC, Mooyeee commented
Hey, my bad for the formatting, it was done by the software I use to edit md files (MarkText), now it should be ok. I also added the part as requested, let me know if it's alright or if there are other changes needed! :)
I'll try to experiment a little with smk too since this isn't my main board.

2024-04-27 21:57 UTC, carlossless commented on src/part.rs
> +    "leobog-hi-75" => PART_LEOBOG_HI75,
```suggestion
    "leobog-hi75" => PART_LEOBOG_HI75,
```

2024-04-28 07:38 UTC, carlossless approved these changes
LGTM

2024-04-28 07:39 UTC, merged